Fiorello-PB101-Demo/Controllers/HomeController.cs
using Fiorello_PB101_Demo.Services.Interfaces;
using Fiorello_PB101_Demo.ViewModels;
using Fiorello_PB101_Demo.ViewModels.Baskets;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Newtonsoft.Json;
using System.Diagnostics.Eventing.Reader;

namespace Fiorello_PB101_Demo.Controllers
{
    public class HomeController : Controller
    {
        private readonly ISliderService _sliderService;
        private readonly IBlogService _blogService;
        private readonly IExpertService _expertService;
        private readonly ICategoryService _categoryService;
        private readonly IProductService _productService;
        private readonly IHttpContextAccessor _accessor;

        public HomeController(
            ISliderService sliderService,
            IBlogService blogService,
            IExpertService expertService,
            ICategoryService categoryService,
            IProductService productService,
            IHttpContextAccessor accessor
            )
        {
            _sliderService = sliderService;
            _blogService = blogService;
            _expertService = expertService;
            _categoryService = categoryService;
            _productService = productService;
            _accessor = accessor;
        }
        public async Task<IActionResult> Index()
        {
          
            HomeVM model = new()
            {
                Blogs = await _blogService.GetAllAsync(3),
                Experts = await _expertService.GetAllAsync(),
                Categories = await _categoryService.GetAllAsync(),
                Products = await _productService.GetAllAsync()
            };

            return View(model);
        
        }
         
        [HttpPost]
        public async Task<IActionResult> AddProductToBasket(int? id)
        {
            if (id is null) return BadRequest();

            var product = await _productService.GetByIdAsync((int)id);

            if (product == null) return NotFound();

            List<BasketVM> basketDatas;

            if (_accessor.HttpContext.Request.Cookies["basket"] is not null)
            {
                basketDatas = JsonConvert.DeserializeObject<List<BasketVM>>(_accessor.HttpContext.Request.Cookies["basket"]);
            }
            else
            {
                basketDatas = new List<BasketVM>();
            }

            var existBasketData = basketDatas.FirstOrDefault(m=>m.Id == id);

            if (existBasketData != null)
            {
                existBasketData.Count++;
            }
            else
            {

                basketDatas.Add(new BasketVM
                {
                    Id = (int)id,
                    Price = product.Price,
                    Count = 1
                });

            }


            _accessor.HttpContext.Response.Cookies.Append("basket",JsonConvert.SerializeObject(basketDatas));

            int count = basketDatas.Sum(m => m.Count);
            decimal totalPrice = basketDatas.Sum(m=>m.Count * m.Price);

            return Ok(new { count,totalPrice});
        
        }
    }
}

Fiorello-PB101-Demo/Controllers/ProductController.cs
using Fiorello_PB101_Demo.Models;
using Fiorello_PB101_Demo.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace Fiorello_PB101_Demo.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductService _productService;

        public ProductController(IProductService productService)
        {
            _productService = productService;
        }

        public async Task<IActionResult> Index(int? id)
        {
            string hashData = Guid.NewGuid().ToString();
            ViewBag.Hash = hashData;
            if (id is null) return BadRequest();
            Product product = await _productService.GetByIdWithAllDatasAsync((int)id);
            if (product is null) return NotFound();
            return View(product);
        }


    }
}

Fiorello-PB101-Demo/ViewComponents/SliderViewComponent.cs
using Fiorello_PB101_Demo.Models;
using Fiorello_PB101_Demo.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace Fiorello_PB101_Demo.ViewComponents
{
    public class SliderViewComponent : ViewComponent
    {
        private readonly ISliderService _sliderService;
        public SliderViewComponent(ISliderService sliderService)
        {
            _sliderService = sliderService;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var sliderDatas = new SliderVMC
            {
                Sliders = await _sliderService.GetAllAsync(),
                SliderInfo = await _sliderService.GetSliderInfoAsync(),
            };

            return await Task.FromResult(View(sliderDatas));
        }
    }

    public class SliderVMC
    {
        public IEnumerable<Slider> Sliders { get; set; }
        public SliderInfo SliderInfo { get; set; }
    }
}

Fiorello-PB101-Demo/Views/Home/Index.cshtml
@model HomeVM
@{
    ViewData["Title"] = "Home";
}

  <!-- MAIN START -->

    <main>

        <!-- SLIDER START -->

       @await Component.InvokeAsync("Slider")

        <!-- SLIDER END -->

        <!-- PRODUCTS START -->

        <section id="products">
            <div class="container">
                <div class="row pt-5">
                    <div class="col-12 d-flex justify-content-between">
                        <ul class="category-mobile d-md-none list-unstyled">
                            <li>
                                <a href="" class="categories mr-2">Categories</a>
                                <i class="fas fa-caret-down"></i>
                                <ul class="category list-unstyled" style="display: none;">
                                    <li><a href="" data-id="all">All</a></li>
                                    <li><a href="" data-id="popular">Popular</a></li>
                                    <li><a href="" data-id="winter">Winter</a></li>
                                    <li><a href="" data-id="various">Various</a></li>
                                    <li><a href="" data-id="exotic">Exotic</a></li>
                                    <li><a href="" data-id="green">Greens</a></li>
                                    <li><a href="" data-id="cactuse">Cactuses</a></li>
                                </ul>
                            </li>
                        </ul>
                        <ul class="category d-none d-md-flex list-unstyled">
                            <li><a href="" data-id="all">All</a></li>
                           @foreach (var item in Model.Categories)
                            {
                                <li><a href="" data-id="@item.Id">@item.Name</a></li>
                            }
                           
                        </ul>
                        <ul class="list-unstyled">
                            <li>
                                <a href="" class="mr-2">Filter</a>
                                <i class="fas fa-caret-down"></i>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="row">
                   @foreach (var item in Model.Products)
                   {
                    <div class="col-sm-6 col-md-4 col-lg-3 mt-3">
                        <div class="product-item text-center" data-id="@item.CategoryId">
                            <div class="img">
                                <a asp-controller="Product" asp-action="Index" asp-route-id="@item.Id">
                                    <img src="~/img/@item.ProductImages.FirstOrDefault(m=> m.IsMain)?.Name" class="img-fluid" alt="">
                                </a>
                            </div>
                            <div class="title mt-3">
                                <h6>@item.Name</h6>
                            </div>
                            <div class="price">
                                   <span class="add-basket" data-id="@item.Id">Add to Cart</span>                        
                                <span class="text-black-50">$@item.Price.ToString(@item.Price % 1 == 0 ? "0" : "0.00")</span>
                            </div>
                        </div>
                    </div>

                   }
                </div>
            </div>
        </section>

        <!-- PRODUCTS END -->

        <!-- ABOUT START -->

        <section id="about">
            <div class="container py-5">
                <div class="row py-5">
                    <div class="col-lg-6">
                        <div class="img">
                            <img src="~/img/h3-video-img.jpg" class="img-fluid" alt="">
                            <div
                                class="player position-absolute rounded-circle d-flex align-items-center justify-content-center">
                                <i class="fas fa-play fa-lg"></i>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="about-text mt-5 mt-lg-0 px-lg-5">
                            <h1>Suprise Your <span>Valentine!</span> Let us arrange a smile.</h1>
                            <p class="py-3">Where flowers are our inspiration to create lasting memories. Whatever the
                                occasion...</p>
                            <ul class="list-unstyled">
                                <li class="mt-3"><img src="~/img/h1-custom-icon.png" class="mr-2" alt=""> Hand picked just
                                    for you.</li class="mt-3">
                                <li class="mt-3"><img src="~/img/h1-custom-icon.png" class="mr-2" alt=""> Unique flower
                                    arrangements</li>
                                <li class="mt-3"><img src="~/img/h1-custom-icon.png" class="mr-2" alt=""> Best way to say
                                    you care.</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <!-- ABOUT END -->

        <!-- EXPERTS START -->

        <section id="experts">
            <div class="container">
                <div class="row py-5">
                    <div class="offset-lg-3 col-lg-6">
                        <div class="section-title">
                            <h1>Flower Experts</h1>
                            <p class="text-black-50">A perfect blend of creativity, energy, communication, happiness and
                                love. Let us arrange
                                a smile for you.</p>
                        </div>
                    </div>
                </div>
                <div class="row pb-5">
                    @foreach (var item in Model.Experts)
                    {
                        <div class="col-md-6 col-lg-3">
                            <div class="item text-center">
                                <div class="img">
                                    <img src="~/img/@item.Image" class="img-fluid rounded-circle" alt="">
                                </div>
                                <div class="text mt-3">
                                    <h6>@item.FullName.ToUpper()</h6>
                                    <p class="text-black-50">@item.Position</p>
                                </div>
                            </div>
                        </div>
                    }
                    <div class="col-lg-3"></div>
                    <div class="col-lg-3"></div>
                    <div class="col-lg-3"></div>
                </div>
            </div>
        </section>

        <!-- EXPERTS END -->

        <!-- SUBSCRIBE START -->

        <section id="subscribe">
            <div class="container py-5">
                <div class="row py-5">
                    <div class="col-12">
                        <div class="content text-center py-5">
                            <h3>Join The Colorful Bunch!</h3>
                            <div class="form-group d-flex justify-content-center flex-wrap mt-5">
                                <input type="email" placeholder="Email Address" class="form-control-lg rounded-0">
                                <button class="btn btn-danger btn-lg rounded-0 px-5 mt-3 mt-sm-0">Subscribe</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <!-- SUBSCRIBE END -->

        <!-- BLOG START -->

        <section id="blog">
            <div class="container">
                <div class="row py-5">
                    <div class="offset-lg-3 col-lg-6">
                        <div class="section-title">
                            <h1>From our Blog</h1>
                            <p class="text-black-50">A perfect blend of creativity, energy, communication, happiness and
                                love. Let us arrange
                                a smile for you.</p>
                        </div>
                    </div>
                </div>
              <partial name="_BlogPartial" model="@Model.Blogs"/>
            </div>
        </section>

        <!-- BLOG END -->

        <!-- SAY START -->

        <section id="say">
            <div class="container">
                <div class="row py-5 justify-content-center">
                    <div class="col-md-8 col-xl-6">
                        <div class="owl-carousel say">
                            <div>
                                <div class="item text-center">
                                    <div class="img d-flex justify-content-center">
                                        <img src="~/img/testimonial-img-1.png" alt="">
                                    </div>
                                    <div class="text text-muted pt-3 pb-5">
                                        <i>Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus
                                            lingua. </i>
                                    </div>
                                    <div class="author">
                                        <h6>Anna Barnes</h6>
                                        <p class="text-black-50">Florist</p>
                                    </div>
                                </div>
                            </div>
                            <div>
                                <div class="item text-center">
                                    <div class="img d-flex justify-content-center">
                                        <img src="~/img/testimonial-img-2.png" alt="">
                                    </div>
                                    <div class="text text-muted pt-3 pb-5">
                                        <i>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo
                                            ligula eget. </i>
                                    </div>
                                    <div class="author">
                                        <h6>Jasmine White</h6>
                                        <p class="text-black-50">Florist</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <!-- SAY END -->

        <!-- INSTAGRAM START -->

        <section id="instagram">
            <div class="owl-carousel instagram">
                <div><img src="~/img/instagram1.jpg" class="img-fluid" alt=""></div>
                <div><img src="~/img/instagram2.jpg" class="img-fluid" alt=""></div>
                <div><img src="~/img/instagram3.jpg" class="img-fluid" alt=""></div>
                <div><img src="~/img/instagram4.jpg" class="img-fluid" alt=""></div>
                <div><img src="~/img/instagram5.jpg" class="img-fluid" alt=""></div>
                <div><img src="~/img/instagram6.jpg" class="img-fluid" alt=""></div>
                <div><img src="~/img/instagram7.jpg" class="img-fluid" alt=""></div>
                <div><img src="~/img/instagram8.jpg" class="img-fluid" alt=""></div>
            </div>
            <div class="hastag bg-light text-muted py-2 px-3">
                #FIORELLO
            </div>
        </section>

        <!-- INSTAGRAM END -->

    </main>

    <!-- MAIN END -->